### PR TITLE
Layout

### PR DESCRIPTION
**Pull request by angel-afonso**
# Basic material design scaffold

Reason:
We need a basic design scaffold and because we don't have the money to pay a designer

Before pull request:
The are no component with a design scaffold

After pull request:
A Layout component was added

### CODE REVIEW

**Comment by angel-afonso** [comment]
What if we rename layout to scaffold?

**Comment by HectorZR** [comment]
I agree with you, to keep the same through apps... Make the changes and then we aprove the PR

**Review by HectorZR — CHANGES_REQUESTED** [review]
Everything is okay, only need to change Layout for Scaffold

**Review by HectorZR — APPROVED** [review]
lgtm!

**Pull request merged**
